FORMAT: 1A
HOST: https://private-478a2-livehouston.apiary-mock.com

# LiveHouston API

The LiveHouston API drives the LiveHouston Mobile Apps (iOS and Android)

## Events [/events]

### List all Events [GET]

<!--+ Request-->

  <!--+ Headers-->

  <!--          Authorization: Bearer: SDFSDFSDFSDFSDFSDFIIIII-->
  
  ### Updated Response to match website

  + Response 200 (application/json)

                 [
            {
                "featured" : [
                    {
                      "eventTitle" : "7TH ANNUAL WAVE HOLIDAY LIGHTS TOURS",
                      "date" : "December 13, 2016 - December 22, 2016",
                      "eventLocation" : "ALLEY THEATRE",
                      "event_location_website" : "https://www.visithoustontexas.com/listings/alley-theatre/19464/",
                      "eventAddress" : "1160 W. 26TH STREET | HOUSTON, TX 77008",
                      "eventTimes" : "6:30 PM to 9:30 PM",
                      "eventAdmission" : "$35",
                      "eventDescription" : "First we will go by City Hall to see the awesome tree then Discovery Green, Field of Lights. Then we will head into River Oaks. Last we will drive through Woodland Heights. We will be giving you a chance to get out & walk around at each spot if you want to take some pictures. There is no public restroom once the tour starts until we get to Discovery Green. Our windows are tinted, but you can still see out and most people have wanted to get out & walk around at the stops. You will be able to see all the pictures we take.\nKid friendly. Kids do need a seat, but if you are okay with lapping a child 4 & under, then they do not need a ticket.",
                      "areaOfTown" : "Downtown",
                      "event_website_url" : "https://www.eventbrite.com/e/7th-annual-wave-holiday-lights-tours-tickets-29053805715",
                      "event_image_url" : "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F25752908%2F18565618941%2F1%2Foriginal.jpg?w=800&rect=0%2C0%2C650%2C325&s=039a59c7642a7c5e331a4330902e3a6c",
                      "category" : "Weekend",
                      "tickets_available" : "False",
                      "buy_tickets_url" : ""
                    },
                    {
                      "eventTitle" : "A CHRISTMAS CAROL-A GHOST STORY OF CHRISTMAS",
                      "date" : "November 19, 2016 - December 29, 2016",
                      "eventLocation" : "ALLEY THEATRE",
                      "event_location_website" : "https://www.visithoustontexas.com/listings/alley-theatre/19464/",
                      "eventAddress" : "615 TEXAS AVENUE | HOUSTON, TX 77002",
                      "eventTimes" : "Varies",
                      "eventAdmission" : "$35-$70",
                      "eventDescription" : "First we will go by City Hall to see the awesome tree then Discovery Green, Field of Lights. Then we will head into River Oaks. Last we will drive through Woodland Heights. We will be giving you a chance to get out & walk around at each spot if you want to take some pictures. There is no public restroom once the tour starts until we get to Discovery Green. Our windows are tinted, but you can still see out and most people have wanted to get out & walk around at the stops. You will be able to see all the pictures we take.\nKid friendly. Kids do need a seat, but if you are okay with lapping a child 4 & under, then they do not need a ticket.",
                      "areaOfTown" : "Downtown",
                      "event_website_url" : "https://www.alleytheatre.org/plays/production-detail/christmas-carol",
                      "event_image_url" : "https://placeholdit.imgix.net/~text?txtsize=18&txt=86%C3%97114&w=86&h=114",
                      "category" : "Weekend",
                      "tickets_available" : "True",
                      "buy_tickets_url" : "https://www.alleytheatre.org/plays/production-detail/christmas-carol"
                    }
                  ]
            },
            {
                "ongoing" : [
                    {
                      "eventTitle" : "A CHRISTMAS CAROL-A GHOST STORY OF CHRISTMAS",
                      "date" : "November 19, 2016 - December 29, 2016",
                      "eventLocation" : "ALLEY THEATRE",
                      "event_location_website" : "https://www.visithoustontexas.com/listings/alley-theatre/19464/",
                      "eventAddress" : "615 TEXAS AVENUE | HOUSTON, TX 77002",
                      "eventTimes" : "Varies",
                      "eventAdmission" : "$35-$70",
                      "eventDescription" : "First we will go by City Hall to see the awesome tree then Discovery Green, Field of Lights. Then we will head into River Oaks. Last we will drive through Woodland Heights. We will be giving you a chance to get out & walk around at each spot if you want to take some pictures. There is no public restroom once the tour starts until we get to Discovery Green. Our windows are tinted, but you can still see out and most people have wanted to get out & walk around at the stops. You will be able to see all the pictures we take.\nKid friendly. Kids do need a seat, but if you are okay with lapping a child 4 & under, then they do not need a ticket.",
                      "areaOfTown" : "Downtown",
                      "event_website_url" : "https://www.alleytheatre.org/plays/production-detail/christmas-carol",
                      "event_image_url" : "https://placeholdit.imgix.net/~text?txtsize=18&txt=86%C3%97114&w=86&h=114",
                      "category" : "Weekend",
                      "tickets_available" : "True",
                      "buy_tickets_url" : "https://www.alleytheatre.org/plays/production-detail/christmas-carol"
                    },
                    {
                      "eventTitle" : "A CHRISTMAS CAROL-A GHOST STORY OF CHRISTMAS",
                      "date" : "November 19, 2016 - December 29, 2016",
                      "eventLocation" : "ALLEY THEATRE",
                      "event_location_website" : "https://www.visithoustontexas.com/listings/alley-theatre/19464/",
                      "eventAddress" : "615 TEXAS AVENUE | HOUSTON, TX 77002",
                      "eventTimes" : "Varies",
                      "eventAdmission" : "$35-$70",
                      "eventDescription" : "First we will go by City Hall to see the awesome tree then Discovery Green, Field of Lights. Then we will head into River Oaks. Last we will drive through Woodland Heights. We will be giving you a chance to get out & walk around at each spot if you want to take some pictures. There is no public restroom once the tour starts until we get to Discovery Green. Our windows are tinted, but you can still see out and most people have wanted to get out & walk around at the stops. You will be able to see all the pictures we take.\nKid friendly. Kids do need a seat, but if you are okay with lapping a child 4 & under, then they do not need a ticket.",
                      "areaOfTown" : "Downtown",
                      "event_website_url" : "https://www.alleytheatre.org/plays/production-detail/christmas-carol",
                      "event_image_url" : "https://placeholdit.imgix.net/~text?txtsize=18&txt=86%C3%97114&w=86&h=114",
                      "category" : "Weekend",
                      "tickets_available" : "True",
                      "buy_tickets_url" : "https://www.alleytheatre.org/plays/production-detail/christmas-carol"
                    }
                  ]
            }
        ]
          
## Things To Do Categories [/thingscategories]

### List all Things To Do Categories [GET]

  + Response 200 (application/json)
  
        {
            "thingsCategories": [
                "Live Music",
                "Dating",
                "Free Things",
                "CityPASS",
                "Houston & Beyond",
                "Kids",
                "Museums",
                "Shopping".
                "Performing Arts",
                "Sports",
                "Tours",
                "Parks & Outdoors",
                "Golf Courses",
                "Spas & Fitness",
                "Historic Sites",
                "Creative Classes",
                "Other"
            ]
        },
        {
            "eventCategories": [
                "Holiday Lights",
                "Annual Events",
                "Kid-Friendly",
                "Concerts & Live Music",
                "Free",
                "Festivals",
                "Sports",
                "Food & Drink".
                "Outdoor",
                "Museum Exhibitions",
                "Theater & Performing Arts"
            ]
        }